using System;

[AttributeUsage(AttributeTargets.All, Inherited = true, AllowMultiple = true)]
public sealed class AIGeneratedAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="AIGeneratedAttribute"/> class.
    /// </summary>
    /// <param name="guid">
    /// A unique identifier for the generated code block (as a string representation of a GUID).
    /// </param>
    /// <param name="timeStamp">
    /// The timestamp when the code was generated, in ISO 8601 format.
    /// </param>
    /// <param name="confidence">
    /// A value between 0 and 100 representing the AI generation confidence. Default is 100.
    /// </param>
    public AIGeneratedAttribute(string guid, string timeStamp, int confidence = 100)
    {
        if (string.IsNullOrWhiteSpace(guid))
            throw new ArgumentException("GUID must be a non-empty string.", nameof(guid));
        if (string.IsNullOrWhiteSpace(timeStamp))
            throw new ArgumentException("TimeStamp must be a non-empty string.", nameof(timeStamp));

        Guid = guid;
        TimeStamp = timeStamp;
        Confidence = confidence;
    }

    /// <summary>
    /// Gets the unique identifier for the generated code block.
    /// </summary>
    public string Guid { get; }

    /// <summary>
    /// Gets the timestamp when the code was generated (ISO 8601 format).
    /// </summary>
    public string TimeStamp { get; }

    /// <summary>
    /// Gets the AI generation confidence level.
    /// </summary>
    public int Confidence { get; }

    /// <summary>
    /// Gets or sets the name of the AI tool or agent responsible for code generation.
    /// </summary>
    public string? AgentName { get; set; }

    /// <summary>
    /// Gets or sets additional metadata as a semicolon-delimited string
    /// (e.g., "version=1.0;module=MyModule").
    /// </summary>
    public string? Metadata { get; set; }

    /// <summary>
    /// Gets or sets an array of text span ranges (encoded as "start,length")
    /// that represent parts of the code modified or generated by AI.
    /// </summary>
    public string[]? TextSpanRanges { get; set; }

    /// <summary>
    /// Gets or sets a flag indicating whether review diagnostics should be enabled.
    /// </summary>
    public bool EnableReviewDiagnostics { get; set; }
}

[AIGenerated(
    guid: "d9f88d0e-6f0a-4d4e-9f4c-123456789abc",
    timeStamp: "2025-02-14T10:00:00Z",
    confidence: 95,
    AgentName = "GPT-4",
    Metadata = "version=1.0;module=MyModule",
    TextSpanRanges = ["10,5", "20,3"],
    EnableReviewDiagnostics = true)]
public class GeneratedClass
{
    // Class implementation
}
